"""Original CC0 ideal-interface geometry; no rendered images or goldens."""
import hashlib,json,struct,sys
from pathlib import Path
out=Path(sys.argv[1]);out.mkdir(parents=True,exist_ok=False)
records=[]
for variant in ['single','slab','tilted']:
    binary=bytearray();views=[];accessors=[]
    def accessor(values,kind,components):
        while len(binary)%4:binary.append(0)
        offset=len(binary);flat=[v for row in values for v in row];binary.extend(struct.pack('<'+'f'*len(flat),*flat))
        views.append({'buffer':0,'byteOffset':offset,'byteLength':len(flat)*4})
        a={'bufferView':len(views)-1,'componentType':5126,'count':len(values),'type':kind}
        if kind=='VEC3' and components=='position':a.update(min=[min(v[j] for v in values) for j in range(3)],max=[max(v[j] for v in values) for j in range(3)])
        accessors.append(a);return len(accessors)-1
    meshes=[]
    for name,normal in [('glass',[.6,0,.8] if variant=='tilted' else [0,0,1]),('exit',[0,0,-1]),('emitter',[0,0,1])]:
        # Reverse exit geometry winding as well as its authored frame.
        points=[[-1,-1,0],[1,-1,0],[1,1,0],[-1,-1,0],[1,1,0],[-1,1,0]]
        if name=='exit':points=[points[j] for j in [0,2,1,3,5,4]]
        attrs={'POSITION':accessor(points,'VEC3','position'),'NORMAL':accessor([normal]*6,'VEC3','normal'),'TEXCOORD_0':accessor([[(p[0]+1)/2,(p[1]+1)/2] for p in points],'VEC2','uv')}
        meshes.append({'name':name,'primitives':[{'attributes':attrs,'material':1 if name=='emitter' else 0}]})
    nodes=[{'name':'glass-front','mesh':0},{'name':'emitter-target','mesh':2,'translation':[0,0,-2 if variant=='slab' else -1],'scale':[4,4,1]}]
    if variant=='slab':nodes.append({'name':'glass-exit','mesh':1,'translation':[0,0,-1]})
    doc={'asset':{'version':'2.0','generator':'Original CC0 GPU ideal-interface fixture'},'scene':0,'scenes':[{'nodes':list(range(len(nodes)))}],'nodes':nodes,'meshes':meshes,'materials':[
        {'name':'glass','pbrMetallicRoughness':{'baseColorFactor':[.8,.9,1,1],'metallicFactor':0,'roughnessFactor':0},'doubleSided':False},
        {'name':'emitter','pbrMetallicRoughness':{'baseColorFactor':[0,0,0,1],'metallicFactor':0,'roughnessFactor':1},'emissiveFactor':[.75,.5,.25],'doubleSided':False}],
        'buffers':[{'byteLength':len(binary)}],'bufferViews':views,'accessors':accessors}
    encoded=json.dumps(doc,separators=(',',':')).encode();encoded+=b' '*((-len(encoded))%4);payload=bytes(binary)+b'\0'*((-len(binary))%4)
    glb=struct.pack('<III',0x46546c67,2,12+8+len(encoded)+8+len(payload))+struct.pack('<II',len(encoded),0x4e4f534a)+encoded+struct.pack('<II',len(payload),0x004e4942)+payload
    (out/(variant+'.glb')).write_bytes(glb);(out/(variant+'.bin')).write_bytes(binary)
    doc['buffers'][0]['uri']=variant+'.bin';(out/(variant+'.gltf')).write_text(json.dumps(doc,indent=2)+'\n')
    records.append({'variant':variant,'glb_sha256':hashlib.sha256(glb).hexdigest()})
(out/'provenance.json').write_text(json.dumps({'license':'CC0-1.0','source':'Original geometry, normals and material recipes generated by fixtures/gpu-dielectric/generate.py','scope':'Native dielectric is authored after import; no glTF transmission extension is claimed','variants':records},indent=2)+'\n')
# Independent camera/transaction recipes and sampled analytic expectations.
import math
f32=lambda x:struct.unpack('<f',struct.pack('<f',x))[0]
def random(sample,dimension):
    x=((sample*2891336453)&0xffffffff)^((dimension*277803737)&0xffffffff)^42
    x=(((x>>((x>>28)+4))^x)*277803737)&0xffffffff;x=(x>>22)^x
    return ((x>>8)+.5)/16777216
analytic=[]
for name,variant,ior in [('single-ior1','single',1),('single-ior1_5','single',1.5),('single-ior3','single',3),('slab-ior1','slab',1),('slab-ior1_5','slab',1.5),('slab-ior3','slab',3),('tilted-frame','tilted',1.5),('mirror-x','single',1.5),('mirror-z','single',1.5),('snell','single',1.5),('tir','single',1.5),('grazing','single',1.5),('near-clipped','single',1.5),('far-clipped','single',1.5),('mask-clear','single',1.5),('blend-half','single',1.5)]:
    camera={'position':[0,0,1],'target':[0,0,0],'lens':{'kind':'orthographic','xmag':1e-7,'ymag':1e-7,'near':.01,'far':10}}
    transforms=[]
    if name.startswith('mirror'):
        cols=[[1,0,0],[0,1,0],[0,0,1],[0,0,0]];axis=0 if name=='mirror-x' else 2;cols[axis][axis]=-1;transforms.append({'name':'glass-front','transform':{'columns':cols,'operations':[]}})
    if name in ['snell','tir','grazing']:
        if name=='snell':camera['position']=[-.5/math.sqrt(.75),0,1];x=1/math.sqrt(8)
        elif name=='tir':camera['position']=[-.5*.9/math.sqrt(.19),0,-.5];x=.9/math.sqrt(.19)
        else:camera['position']=[-.5*math.sqrt(.99)/.1,0,.5];x=math.sqrt(.99/2.25)/math.sqrt(1-.99/2.25)
        transforms.append({'name':'emitter-target','transform':{'columns':[[.05,0,0],[0,4,0],[0,0,1],[x,0,-1]],'operations':[]}})
    if name=='near-clipped':camera['lens']['near']=1.1
    if name=='far-clipped':camera['lens']['far']=.9
    opacity={'kind':'mask','factor':0,'cutoff':.5} if name=='mask-clear' else {'kind':'blend','factor':.5} if name=='blend-half' else {'kind':'opaque'}
    fresnel=.04152262597582152 if name=='snell' else .5715925203424491 if name=='grazing' else ((ior-1)/(ior+1))**2
    count=sum(random(s,6)>=fresnel and (variant!='slab' or random(s,22)>=fresnel) for s in range(16))
    expected=[]
    for tint,emission in zip([f32(.8),f32(.9),1],[.75,.5,.25]):
        if name=='far-clipped':v=0
        elif name in ['tir','near-clipped','mask-clear']:v=emission
        elif name=='blend-half':v=emission*sum(1 if random(s,1024)>=.5 else tint/(ior*ior) if random(s,6)>=fresnel else 0 for s in range(16))/16
        else:v=emission*(tint*tint if variant=='slab' else tint*ior*ior if name=='mirror-z' else tint/(ior*ior))*count/16
        expected.append(f32(v))
    analytic.append({'name':'analytic-'+name,'source':'fixtures/gpu-dielectric/data/'+variant+'.glb','source_sha256':hashlib.sha256((out/(variant+'.glb')).read_bytes()).hexdigest(),'model':{'kind':'dielectric','ior':ior},'opacity':opacity,'animated':False,'secondary':True,'glass_only':True,'settings':{'width':1,'height':1,'samples':16,'seed':42,'max_depth':3 if variant=='slab' else 2},'camera':camera,'transforms':transforms,'expected':expected})
(out/'analytic-cases.json').write_text(json.dumps({'license':'CC0-1.0','oracle':'Snell target geometry, geometric-interface Fresnel/radiance factors and independently evaluated counter samples; no renderer outputs','cases':analytic},indent=2)+'\n')
