import json,sys
from pathlib import Path
root=Path(sys.argv[1]);evidence=Path('evidence/tiled-painting')
validation=json.loads((root/'validation_report.json').read_text());assert validation['status']=='passed'
collection=json.loads((evidence/'collection.json').read_text());assert collection['status']=='passed'
workflow=json.loads((evidence/'paint-workflow/workflow_report.json').read_text());cross=json.loads((evidence/'paint-workflow/cross_platform.json').read_text())
assert workflow['status']==cross['status']=='passed'
def replace(path,old,new):
 p=Path(path);s=p.read_text();assert old in s,path;p.write_text(s.replace(old,new))
replace('docs/tiled_painting.md','# Tiled painting candidate: paint-tiles-v1','# Tiled painting: paint-tiles-v1')
replace('docs/tiled_painting.md','This M10 engine candidate is under validation. Qualified UV authoring remains\navailable independently.','This bounded M10 engine profile passed its [acceptance gates](../evidence/tiled-painting/README.md).\nQualified UV authoring remains available independently.')
replace('docs/tiled_painting.md','Unknown or unsupported fields reject. No capability status is raised by this\ncandidate document; native/Wasm, fixture, storage, renderer and provenance gates\nmust pass first.','Unknown or unsupported fields reject. Qualification covers the measured bounded\nworkflow, with native/Wasm, fixture, storage, renderer and provenance evidence.\nIt does not extend support to these separate capabilities.')
replace('docs/decision_records.md','**Candidate decision:** Keep independent canvas IDs','**Decision:** Keep independent canvas IDs')
replace('docs/decision_records.md','[paint-tiles-v1](tiled_painting.md) is under validation.\nKeep native/browser tile, PNG and revision equality, analytic alpha/locality tests,\nresource observations and prior artifact preservation as gates.','[paint-tiles-v1](tiled_painting.md) passed the bounded\nnative/browser tile, PNG and revision equality, analytic alpha/locality tests,\nresource observations and prior artifact preservation gates. See `evidence/tiled-painting`.')
replace('fixtures/tiled-painting/README.md','This candidate is not yet qualified.','The bounded workflow is qualified in `evidence/tiled-painting`.')
replace('planning/engine-progress/tiled-painting-contract.md','# Proposed next M10 engine subgate: tiled texture painting','# Tiled painting engine contract')
replace('planning/engine-progress/tiled-painting-contract.md','Proceed after UV authoring is qualified.','Implemented on qualified UV baseline be20d1f.')
replace('planning/engine-progress/tiled-painting-contract.md','This is a design draft only.','The bounded profile is qualified in `evidence/tiled-painting`.')
replace('planning/engine-progress/tiled-painting-contract.md','No global imaging transfer functions or existing image goldens change.','General floating-point transfer sources and existing image goldens stay unchanged.\nDecoded sRGB8 and mip rounding use the explicit portability profiles in ADR-036/037.')
replace('planning/engine-progress/tiled-painting-contract.md','Capability status remains unqualified until this complete workflow passes.','This bounded workflow passed; see `evidence/tiled-painting/README.md`.')

p=Path('docs/project_cli.md');p.write_text(p.read_text()+'''\n`author_paint` applies bounded pixel-space strokes to an independently bound canvas.\n`bake_paint` composites a pinned canvas into an ordinary PNG image asset. Both use\nordinary durable transactions and return source/output identities and resource\nreports. Layer/canvas setup and explicit image-to-material binding use `apply`. See\n[tiled painting](tiled_painting.md) for checkpointing, masks, color math and limits.\n''')
p=Path('docs/api_and_agent_contracts.md');p.write_text(p.read_text()+'''\nThe shared `author_paint` and `bake_paint` methods prepare bounded tile/image changes\nand publish through ordinary transactions. Editable canvas assets remain distinct\nfrom rendered images and shared materials. `schemas/tiled_painting.schema.json` and\n[the painting contract](tiled_painting.md) specify wire shape and semantics. The\nexisting narrow ABI is unchanged; browser stroke admission remains synchronous.\n''')
p=Path('planning/feature_matrix.json');v=json.loads(p.read_text());assert not any(r['id']=='texture_painting' for r in v['features']);i=next(i for i,r in enumerate(v['features']) if r['id']=='sculpt')
v['features'].insert(i,dict(id='texture_painting',family='Tiled texture painting',status='implemented_experimental_profile',first_useful_gate='M10',broader_gates=['M14'],qualification='paint-tiles-v1: bounded pixel-space strokes, premultiplied UNORM16 tiles, scalar layer masks, layers, checkpoint recovery and explicit RGBA8 PNG baking. Projected painting, HDR, virtual textures and broader baking remain separate.',capability_axes=dict(native_authoring='ordinary_canvas_tile_asset_transactions_and_author_paint',native_evaluation='bounded_layer_mask_composite_and_explicit_bake_paint',final_render='validated_named_UV_to_painted_image_CPU_Metal_WebGPU_workflow',preview='shared_Rust_rendering; no_paint_editor',human_editing='planned_M09',**{'import':'native_typed_tiles_and_stroke_recipes; no_external_layer_stack_import','export':'snapshot18_archive_and_normal_baked_PNG_image_asset'}),platform_profiles=dict(native_desktop='validated_macos_arm64; linux_windows_compile_only',browser_local='validated_Chromium_Rust_Wasm_OPFS_WebGPU; synchronous_bounded_authoring'),evidence=['evidence/tiled-painting/README.md']))
v['features'][0]['qualification']='Transactional typed assets and shared geometry through snapshot version 18, with procedural, groom, media, UV and paint assets, animation and imaging; no full editor.';p.write_text(json.dumps(v,indent=2)+'\n')
p=Path('planning/milestones.json');v=json.loads(p.read_text());m=next(r for r in v['milestones'] if r['id']=='M10');assert m['status']=='in_progress';m['engine_subgates'].append(dict(id='tiled-painting',status='validated_experimental_profile',evidence='evidence/tiled-painting/README.md'));m['remaining']='Projected painting and broader baking, sculpting, masks/face sets/symmetry, multiresolution, remesh, retopology and the deferred M09 interactive demonstration.';p.write_text(json.dumps(v,indent=2)+'\n')
p=Path('planning/engine-progress/README.md');s=p.read_text().replace('Current completed increment: bounded UV unwrap/packing and named constraint assets; evidence/uv-authoring.','Current completed increment: tiled texture painting, masks/layers, checkpoint recovery and explicit image baking; evidence/tiled-painting.').replace('Next engine subgate: tiled texture painting, layers, masks and explicit image baking.','Next engine subgate: localized sculpt authoring, spatial queries and sparse displacement/mask chunks.').replace('UV authoring validated; painting, sculpting, remesh and retopology pending','UV and bounded tiled painting validated; sculpting, remesh and retopology pending')
s+=f'''\nTiled painting acceptance: {validation['native_test_count']} native tests,\n{validation['wasm_test_count']} Wasm tests, {len(validation['checks'])} acceptance checks and\n{collection['native_calls']} CLI requests. Layer/mask/erase, checkpoint recovery,\nexplicit PNG baking, named UV material binding, old-client rejection, archive/OPFS\nrecovery and CPU/Metal/WebGPU output passed. {collection['render_artifact_count']} prior\nrender/pass/receipt files remain byte identical. No Cargo or shader changes.\nM10 and the M09 interactive dependency remain open.\n''';p.write_text(s)
p=Path('planning/engine-progress/paint-numerical-provenance.json');v=json.loads(p.read_text());v['status']='validated_experimental_profile';v['decoded_srgb8_profile']['prior_native_outputs_preserved']=True;v['prior_render_artifacts_preserved']=collection['render_artifact_count'];p.write_text(json.dumps(v,indent=2)+'\n')
p=Path('planning/engine-progress/tiled-painting-interface-review.md');p.write_text(p.read_text()+'''\nIntegration acceptance passed on be20d1f: native/Wasm tile and PNG bytes, revisions,\nreports and CPU pixels agree. Earlier fixture/render/pass/receipt artifacts, Cargo\nand shader outputs remain unchanged. Failure evidence retains a corrected analytic\nrounding expectation, lint failure and interrupted run for a reproduced duplicate\nendpoint dab, with a regression test for the corrected behavior. The browser replay harness also
retains a corrected mutable-request capture failure; unchanged native requests were
rerun, and only hash-verified compiled checks were reused for that continuation.
A subsequent fresh full run validates the source-bound bake retry fix and portable
sRGB8 conversion and common mip LOD logarithm, preserving native outputs without
relaxing exact CPU equality.\n''')
(evidence/'README.md').write_text(f'''# Tiled painting acceptance\n\nThe bounded `paint-tiles-v1` engine profile passed on UV baseline be20d1f. It edits\nimmutable color/mask tiles and explicit layers, continues checkpointed strokes,\nundoes/redoes retained canvases and bakes ordinary PNG images for named UV material\nbinding. M10 sculpting, remeshing, retopology, broader painting/baking and M09 remain\nseparate; this is not an interactive editor completion claim.\n\nThe final run passed {len(validation['checks'])} acceptance checks,\n{validation['native_test_count']} native tests and {validation['wasm_test_count']} Wasm tests.\nA supplementary review strengthened GPU depth/normal checks against the same tested\nartifacts; `paint_pass_review.json` retains the comparator hashes and result.\nThe {collection['native_calls']}-request CLI workflow unwraps/packs a box, paints across\ntile boundaries with pressure, adds a layer and mask, erases, checkpoints, recovers,\nbakes, binds the image, renders and archives/reopens. Actual prior binaries reject\nthe new commands and snapshot18 checkpoints without creating state.\n\nThe exact packaged browser Wasm reproduces tile/image hashes, full snapshots,\nnumerical reports, revisions and CPU pixels/passes. OPFS recovery preserves edits.\nCPU/Metal RMSE is {workflow['cpu_metal_rmse']:.12g}; browser CPU/WebGPU RMSE is\n{cross['browser_cpu_gpu_rmse']:.12g}; Metal/WebGPU maximum channel error is\n{cross['metal_webgpu_max_channel_error']:.12g}. Painted output changes the original\nchecker render by up to {workflow['paint_sampling_max_change']:.9g} linear channel units.\n\nThe corpus retains {collection['render_artifact_count']} prior render/pass/receipt\nfiles and {collection['prior_fixture_files']} prior fixture files byte for byte. All\nfive shaders and Cargo/resolved dependency/native-link profiles are unchanged.\n{collection['new_fixture_files']} new input files reproduce identically. Runtime\nevidence is macOS ARM64 and Chrome; Linux and Windows receive compile checks.\n\n`resources.json` records per-operation work, touched tile copies, output bytes and\nprocess observations. These are not allocator caps or comparative benchmarks;\nother Cargo workloads were active on the host. Dense bake and journal amplification\nremain distinct from sparse tile edits. `development/` preserves failures and the\ninterrupted acceptance run for a duplicate endpoint dab found during review, plus the corrected browser request-capture harness
failure and hash-verified acceptance continuation. The\nnew analytic regression requires nine dabs over eight spacings, including decimal\nendpoints. Bake retries pin canvas/source identity even when PNG bytes match.
The new portable sRGB8 table preserves all 256 qualified native conversion values;
its Decimal64 analytic error bound and generator provenance are retained in
`srgb8_numeric_source.json`. This resolves 23 one-bit platform power differences. Shared Rust f64 log2 rounded
to f32 also preserves all 1,041 observed native mip footprints, removing 144
platform logarithm differences; see `mip_lod_numeric_source.json`.
No render goldens were regenerated.\n\nReproduce using `scripts/validate-tiled-painting.py`, then\n`scripts/collect-tiled-painting-evidence.py <run> <fresh-evidence-directory>`. Supply\n`RENDER_BLEND_REFERENCE_PATH`, `RENDER_BLEND_BASELINE_HOST`,\n`RENDER_UV_BASELINE_HOST`, `RENDER_PAINT_BASELINE_HOST` and\n`RENDER_PAINT_PREVIOUS_RUN` from the retained workflow/baseline records. Serve the\nexact package on localhost:8781 with Chrome CDP on 9224.\n''')
print('Painting documentation qualified')
