// Generated by render-kernel Rust IR. Do not edit.
@group(0) @binding(0) var<storage, read> geometry: array<vec4<f32>>;
@group(0) @binding(1) var<storage, read> instances: array<vec4<f32>>;
@group(0) @binding(2) var<storage, read> params: array<vec4<f32>>;
@group(0) @binding(3) var<storage, read_write> output: array<vec4<f32>>;
@group(0) @binding(4) var<storage, read> texels: array<vec4<f32>>;
fn random(pixel: u32, sample: u32, dimension: u32, seed: u32) -> f32 {
var x: u32 = ((((pixel * 747796405u) ^ (sample * 2891336453u)) ^ (dimension * 277803737u)) ^ seed);
x = (((x >> ((x >> 28u) + 4u)) ^ x) * 277803737u);
x = ((x >> 22u) ^ x);
return ((f32((x >> 8u)) + 0.5) / 16777216.0);
}
fn transform(base: u32, p: vec3<f32>, w: f32) -> vec3<f32> {
return (((((instances[base]).xyz * (p).x) + ((instances[(base + 1u)]).xyz * (p).y)) + ((instances[(base + 2u)]).xyz * (p).z)) + ((instances[(base + 3u)]).xyz * w));
}
fn bounds_hit(ro: vec3<f32>, rd: vec3<f32>, low: vec3<f32>, high: vec3<f32>, limit: f32) -> bool {
var near: f32 = 1e-5;
var far: f32 = limit;
if (((rd).x == 0.0)) {
if ((((ro).x < (low).x) || ((ro).x > (high).x))) {
return false;
}
}
else {
let a: f32 = (((low).x - (ro).x) / (rd).x);
let b: f32 = (((high).x - (ro).x) / (rd).x);
near = max(near, min(a, b));
far = min(far, max(a, b));
if ((far < near)) {
return false;
}
}
if (((rd).y == 0.0)) {
if ((((ro).y < (low).y) || ((ro).y > (high).y))) {
return false;
}
}
else {
let a: f32 = (((low).y - (ro).y) / (rd).y);
let b: f32 = (((high).y - (ro).y) / (rd).y);
near = max(near, min(a, b));
far = min(far, max(a, b));
if ((far < near)) {
return false;
}
}
if (((rd).z == 0.0)) {
if ((((ro).z < (low).z) || ((ro).z > (high).z))) {
return false;
}
}
else {
let a: f32 = (((low).z - (ro).z) / (rd).z);
let b: f32 = (((high).z - (ro).z) / (rd).z);
near = max(near, min(a, b));
far = min(far, max(a, b));
if ((far < near)) {
return false;
}
}
return true;
}
fn triangle_hit(ro: vec3<f32>, rd: vec3<f32>, t: u32, limit: f32) -> vec3<f32> {
let a: vec3<f32> = (geometry[t]).xyz;
let e1: vec3<f32> = ((geometry[(t + 1u)]).xyz - a);
let e2: vec3<f32> = ((geometry[(t + 2u)]).xyz - a);
let p: vec3<f32> = cross(rd, e2);
let det: f32 = dot(e1, p);
if ((abs(det) <= (1e-7 * sqrt(((dot(e1, e1) * dot(e2, e2)) * dot(rd, rd)))))) {
return vec3<f32>(-1.0);
}
let delta: vec3<f32> = (ro - a);
let ucoord: f32 = (dot(delta, p) / det);
if (((ucoord < 0.0) || (ucoord > 1.0))) {
return vec3<f32>(-1.0);
}
let qvec: vec3<f32> = cross(delta, e1);
let vcoord: f32 = (dot(rd, qvec) / det);
if (((vcoord < 0.0) || ((ucoord + vcoord) > 1.0))) {
return vec3<f32>(-1.0);
}
let distance: f32 = (dot(e2, qvec) / det);
if (((distance < 1e-5) || (distance > limit))) {
return vec3<f32>(-1.0);
}
return vec3<f32>(distance, ucoord, vcoord);
}
fn trace(origin: vec3<f32>, direction: vec3<f32>, limit: f32, minimum: f32) -> vec4<f32> {
var closest: f32 = limit;
var result: vec4<f32> = vec4<f32>(vec3<f32>(-1.0), -1.0);
var instance_index: u32 = 0u;
while ((instance_index < u32((params[1u]).w))) {
let base: u32 = (instance_index * 16u);
if (bounds_hit(origin, direction, (instances[(base + 4u)]).xyz, (instances[(base + 5u)]).xyz, closest)) {
let ro: vec3<f32> = transform(base, origin, 1.0);
let rd: vec3<f32> = transform(base, direction, 0.0);
var node: u32 = u32((instances[(base + 6u)]).w);
let end: u32 = u32((geometry[(node + 2u)]).x);
while ((node < end)) {
let low: vec4<f32> = geometry[node];
let high: vec4<f32> = geometry[(node + 1u)];
let escape: u32 = u32((geometry[(node + 2u)]).x);
if (bounds_hit(ro, rd, (low).xyz, (high).xyz, closest)) {
if (((low).w > 0.0)) {
var j: u32 = 0u;
while ((j < u32((low).w))) {
let triangle: u32 = (u32((high).w) + (j * 11u));
let hit: vec3<f32> = triangle_hit(ro, rd, triangle, closest);
if ((((hit).x >= minimum) && (((instances[(base + 8u)]).w > 0.0) || (dot(cross(((geometry[(triangle + 1u)]).xyz - (geometry[triangle]).xyz), ((geometry[(triangle + 2u)]).xyz - (geometry[triangle]).xyz)), rd) < 0.0)))) {
closest = (hit).x;
result = vec4<f32>(closest, f32(instance_index), f32(triangle), 0.0);
}
j = (j + 1u);
}
node = escape;
}
else {
node = (node + 3u);
}
}
else {
node = escape;
}
}
}
instance_index = (instance_index + 1u);
}
return result;
}
fn cosine_direction(normal: vec3<f32>, ucoord: f32, vcoord: f32) -> vec3<f32> {
var helper: vec3<f32> = vec3<f32>(0.0, 0.0, 1.0);
if ((abs((normal).z) >= 0.999)) {
helper = vec3<f32>(1.0, 0.0, 0.0);
}
let tangent: vec3<f32> = normalize(cross(helper, normal));
let bitangent: vec3<f32> = cross(normal, tangent);
let r: f32 = sqrt(ucoord);
let phi: f32 = (6.2831855 * vcoord);
return normalize((((tangent * (r * cos(phi))) + (bitangent * (r * sin(phi)))) + (normal * sqrt((1.0 - ucoord)))));
}
fn camera_origin(pixel_uv: vec2<f32>) -> vec3<f32> {
if (((params[8u]).x == 2.0)) {
return ((((params[3u]).xyz * (((2.0 * (pixel_uv).x) / (params[0u]).x) - 1.0)) * (params[8u]).y) + (((params[4u]).xyz * (1.0 - ((2.0 * (pixel_uv).y) / (params[0u]).y))) * (params[8u]).z));
}
return vec3<f32>(0.0);
}
fn camera_direction(pixel_uv: vec2<f32>) -> vec3<f32> {
if (((params[8u]).x == 2.0)) {
return (params[2u]).xyz;
}
let sx: f32 = (((((2.0 * (pixel_uv).x) / (params[0u]).x) - 1.0) * (params[8u]).w) * (params[2u]).w);
let sy: f32 = ((1.0 - ((2.0 * (pixel_uv).y) / (params[0u]).y)) * (params[2u]).w);
return normalize((((params[2u]).xyz + ((params[3u]).xyz * sx)) + ((params[4u]).xyz * sy)));
}
fn wrap_coord(x: f32, size: f32, mode: f32) -> f32 {
if ((mode == 1.0)) {
return min(max(x, 0.0), (size - 1.0));
}
if ((mode == 2.0)) {
let n: f32 = (x - (floor((x / (2.0 * size))) * (2.0 * size)));
return min(n, (((2.0 * size) - 1.0) - n));
}
return (x - (floor((x / size)) * size));
}
fn texel(level: vec4<f32>, wrap: vec2<f32>, xy: vec2<f32>) -> vec4<f32> {
let x: f32 = wrap_coord((xy).x, (level).y, (wrap).x);
let y: f32 = wrap_coord((xy).y, (level).z, (wrap).y);
let address: u32 = ((u32((level).x) + (u32(y) * u32((level).y))) + u32(x));
let record: vec4<f32> = texels[(address / 2u)];
var pair: vec2<f32> = (record).xy;
if (((address % 2u) == 1u)) {
pair = (record).zw;
}
return vec4<f32>(unpack2x16float(bitcast<u32>((pair).x)), unpack2x16float(bitcast<u32>((pair).y)));
}
fn sample_level(level: vec4<f32>, wrap: vec2<f32>, uv: vec2<f32>, linear: f32) -> vec4<f32> {
var coord: vec2<f32> = uv;
if (((wrap).x == 1.0)) {
(coord).x = min(max((coord).x, 0.0), 1.0);
}
else {
var period: f32 = 1.0;
if (((wrap).x == 2.0)) {
period = 2.0;
}
(coord).x = ((coord).x - (floor(((coord).x / period)) * period));
}
if (((wrap).y == 1.0)) {
(coord).y = min(max((coord).y, 0.0), 1.0);
}
else {
var period: f32 = 1.0;
if (((wrap).y == 2.0)) {
period = 2.0;
}
(coord).y = ((coord).y - (floor(((coord).y / period)) * period));
}
coord = (coord * (level).yz);
if ((linear == 0.0)) {
return texel(level, wrap, floor(coord));
}
coord = (coord - vec2<f32>(0.5, 0.5));
let xy: vec2<f32> = floor(coord);
let fraction: vec2<f32> = (coord - xy);
return ((texel(level, wrap, xy) + ((texel(level, wrap, (xy + vec2<f32>(1.0, 0.0))) - texel(level, wrap, xy)) * (fraction).x)) + (((texel(level, wrap, (xy + vec2<f32>(0.0, 1.0))) + ((texel(level, wrap, (xy + vec2<f32>(1.0, 1.0))) - texel(level, wrap, (xy + vec2<f32>(0.0, 1.0)))) * (fraction).x)) - (texel(level, wrap, xy) + ((texel(level, wrap, (xy + vec2<f32>(1.0, 0.0))) - texel(level, wrap, xy)) * (fraction).x))) * (fraction).y));
}
fn sample_map(descriptor: f32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>) -> vec4<f32> {
if ((descriptor < 0.0)) {
return vec4<f32>(vec3<f32>(1.0), 1.0);
}
let desc: vec4<f32> = geometry[u32(descriptor)];
let filters: vec4<f32> = geometry[(u32(descriptor) + 1u)];
let dims: vec2<f32> = (geometry[u32((desc).x)]).yz;
var lod: f32 = log2(max(max(sqrt(dot((dx * dims), (dx * dims))), sqrt(dot((dy * dims), (dy * dims)))), 1e-8));
if ((lod <= 0.0)) {
return sample_level(geometry[(u32((desc).x) + u32(0.0))], (desc).zw, uv, (filters).x);
}
let mode: f32 = (filters).y;
let linear: f32 = (mode - (floor((mode / 2.0)) * 2.0));
if ((mode < 2.0)) {
return sample_level(geometry[(u32((desc).x) + u32(0.0))], (desc).zw, uv, linear);
}
lod = min(max(lod, 0.0), ((desc).y - 1.0));
if ((mode < 4.0)) {
return sample_level(geometry[(u32((desc).x) + u32(floor((lod + 0.5))))], (desc).zw, uv, linear);
}
let lo: f32 = floor(lod);
return (sample_level(geometry[(u32((desc).x) + u32(lo))], (desc).zw, uv, linear) + ((sample_level(geometry[(u32((desc).x) + u32(min((lo + 1.0), ((desc).y - 1.0))))], (desc).zw, uv, linear) - sample_level(geometry[(u32((desc).x) + u32(lo))], (desc).zw, uv, linear)) * (lod - lo)));
}
fn project_bary(base: u32, triangle: u32, origin: vec3<f32>, direction: vec3<f32>) -> vec3<f32> {
let ro: vec3<f32> = transform(base, origin, 1.0);
let rd: vec3<f32> = transform(base, direction, 0.0);
let a: vec3<f32> = (geometry[triangle]).xyz;
let e1: vec3<f32> = ((geometry[(triangle + 1u)]).xyz - a);
let e2: vec3<f32> = ((geometry[(triangle + 2u)]).xyz - a);
let p: vec3<f32> = cross(rd, e2);
let det: f32 = dot(e1, p);
if ((abs(det) < 1e-20)) {
return vec3<f32>(1.0, 0.0, 0.0);
}
let delta: vec3<f32> = (ro - a);
let b: f32 = (dot(delta, p) / det);
let c: f32 = (dot(rd, cross(delta, e1)) / det);
return vec3<f32>(((1.0 - b) - c), b, c);
}
fn bary_uv(triangle: u32, bary: vec3<f32>) -> vec2<f32> {
return ((((geometry[(triangle + 3u)]).xy * (bary).x) + ((geometry[(triangle + 3u)]).zw * (bary).y)) + ((geometry[(triangle + 4u)]).xy * (bary).z));
}
fn normal_world(base: u32, n: vec3<f32>) -> vec3<f32> {
return normalize(vec3<f32>(dot((instances[base]).xyz, n), dot((instances[(base + 1u)]).xyz, n), dot((instances[(base + 2u)]).xyz, n)));
}
fn vector_world(base: u32, t: vec3<f32>) -> vec3<f32> {
let a: vec3<f32> = (instances[base]).xyz;
let b: vec3<f32> = (instances[(base + 1u)]).xyz;
let c: vec3<f32> = (instances[(base + 2u)]).xyz;
return (vec3<f32>(dot(cross(b, c), t), dot(cross(c, a), t), dot(cross(a, b), t)) / dot(a, cross(b, c)));
}
fn basis_tangent(n: vec3<f32>) -> vec3<f32> {
var helper: vec3<f32> = vec3<f32>(0.0, 0.0, 1.0);
if ((abs((n).z) >= 0.999)) {
helper = vec3<f32>(1.0, 0.0, 0.0);
}
return normalize(cross(helper, n));
}
fn ggx(nh: f32, rough: f32) -> f32 {
let a2: f32 = pow(max(rough, 0.05), 4.0);
let d: f32 = (((nh * nh) * (a2 - 1.0)) + 1.0);
return (a2 / ((3.1415927 * d) * d));
}
fn brdf(color: vec3<f32>, metal: f32, rough: f32, n: vec3<f32>, view: vec3<f32>, light: vec3<f32>) -> vec3<f32> {
let nv: f32 = dot(n, view);
let nl: f32 = dot(n, light);
if ((((nv <= 0.0) || (nl <= 0.0)) || (dot((view + light), (view + light)) < 1e-20))) {
return vec3<f32>(0.0);
}
let h: vec3<f32> = normalize((view + light));
let f0: vec3<f32> = (vec3<f32>(0.04) + ((color - vec3<f32>(0.04)) * metal));
let fresnel: vec3<f32> = (f0 + ((vec3<f32>(1.0) - f0) * pow((1.0 - min(max(dot(view, h), 0.0), 1.0)), 5.0)));
let a2: f32 = pow(max(rough, 0.05), 4.0);
let vis: f32 = (1.0 / ((nl + sqrt((a2 + (((1.0 - a2) * nl) * nl)))) * (nv + sqrt((a2 + (((1.0 - a2) * nv) * nv))))));
return ((((vec3<f32>(1.0) - fresnel) * color) * ((1.0 - metal) / 3.1415927)) + ((fresnel * ggx(max(dot(n, h), 0.0), rough)) * vis));
}
fn pbr_pdf(n: vec3<f32>, view: vec3<f32>, light: vec3<f32>, rough: f32) -> f32 {
if ((((dot(n, light) <= 0.0) || (dot(n, view) <= 0.0)) || (dot((view + light), (view + light)) < 1e-20))) {
return 0.0;
}
let h: vec3<f32> = normalize((view + light));
let vh: f32 = dot(view, h);
if ((vh <= 0.0)) {
return 0.0;
}
return (((0.5 * dot(n, light)) / 3.1415927) + (((0.5 * ggx(max(dot(n, h), 0.0), rough)) * max(dot(n, h), 0.0)) / (4.0 * vh)));
}
fn pbr_sample(n: vec3<f32>, view: vec3<f32>, rough: f32, selector: f32, ucoord: f32, vcoord: f32) -> vec3<f32> {
if ((selector < 0.5)) {
return cosine_direction(n, ucoord, vcoord);
}
let c: f32 = sqrt(((1.0 - ucoord) / (1.0 + ((pow(max(rough, 0.05), 4.0) - 1.0) * ucoord))));
let sine: f32 = sqrt(max((1.0 - (c * c)), 0.0));
let phi: f32 = (6.2831855 * vcoord);
let t: vec3<f32> = basis_tangent(n);
let h: vec3<f32> = normalize((((t * (sine * cos(phi))) + (cross(n, t) * (sine * sin(phi)))) + (n * c)));
return normalize(((h * (2.0 * dot(view, h))) - view));
}
@compute @workgroup_size(64) fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
let pixel: u32 = (gid).x;
let width: u32 = u32((params[0u]).x);
let height: u32 = u32((params[0u]).y);
if ((pixel >= (width * height))) {
return ;
}
var sum: vec3<f32> = vec3<f32>(0.0);
var first_depth: f32 = 0.0;
var first_normal: vec3<f32> = vec3<f32>(0.0);
var first_instance: f32 = -1.0;
var sample: u32 = u32((params[6u]).w);
while ((sample < (u32((params[6u]).w) + u32((params[0u]).z)))) {
let px: f32 = (f32((pixel % width)) + random(pixel, sample, 0u, (u32((params[5u]).w) + (u32((params[7u]).w) * 65536u))));
let py: f32 = (f32((pixel / width)) + random(pixel, sample, 1u, (u32((params[5u]).w) + (u32((params[7u]).w) * 65536u))));
var origin: vec3<f32> = camera_origin(vec2<f32>(px, py));
var direction: vec3<f32> = camera_direction(vec2<f32>(px, py));
var clip_factor: f32 = 1.0;
if (((params[8u]).x == 1.0)) {
clip_factor = (1.0 / dot(direction, (params[2u]).xyz));
}
var throughput: vec3<f32> = vec3<f32>(1.0);
var bounce: u32 = 0u;
var near: f32 = ((params[9u]).x * clip_factor);
var far: f32 = ((params[9u]).y * clip_factor);
while ((bounce < u32((params[0u]).w))) {
var radiance: vec3<f32> = vec3<f32>(0.0);
var weight: vec3<f32> = vec3<f32>(0.0);
var next_origin: vec3<f32> = origin;
var next_direction: vec3<f32> = direction;
let hit: vec4<f32> = trace(origin, direction, far, near);
if (((hit).x < 0.0)) {
radiance = (radiance + (params[7u]).xyz);
}
else {
let base: u32 = (u32((hit).y) * 16u);
let triangle: u32 = u32((hit).z);
let position: vec3<f32> = (origin + (direction * (hit).x));
let a: vec3<f32> = (geometry[triangle]).xyz;
let e1: vec3<f32> = ((geometry[(triangle + 1u)]).xyz - a);
let e2: vec3<f32> = ((geometry[(triangle + 2u)]).xyz - a);
let local_normal: vec3<f32> = cross(e1, e2);
var normal: vec3<f32> = normalize(vec3<f32>(dot((instances[base]).xyz, local_normal), dot((instances[(base + 1u)]).xyz, local_normal), dot((instances[(base + 2u)]).xyz, local_normal)));
if ((dot(normal, direction) > 0.0)) {
normal = (normal * -1.0);
}
if (((sample == u32((params[6u]).w)) && (bounce == 0u))) {
first_depth = (hit).x;
first_normal = normal;
first_instance = (hit).y;
}
if (((instances[(base + 8u)]).z > 0.0)) {
let geometric: vec3<f32> = normal;
let back: bool = (dot(normal_world(base, local_normal), direction) > 0.0);
let bary: vec3<f32> = project_bary(base, triangle, origin, direction);
let uv: vec2<f32> = bary_uv(triangle, bary);
var dx: vec2<f32> = vec2<f32>(0.0, 0.0);
var dy: vec2<f32> = vec2<f32>(0.0, 0.0);
if ((bounce == 0u)) {
dx = (bary_uv(triangle, project_bary(base, triangle, camera_origin(vec2<f32>((px + 1.0), py)), camera_direction(vec2<f32>((px + 1.0), py)))) - uv);
dy = (bary_uv(triangle, project_bary(base, triangle, camera_origin(vec2<f32>(px, (py + 1.0))), camera_direction(vec2<f32>(px, (py + 1.0))))) - uv);
}
var local_shading: vec3<f32> = normalize(local_normal);
if (((geometry[(triangle + 4u)]).z > 0.0)) {
let interpolated: vec3<f32> = ((((geometry[(triangle + 5u)]).xyz * (bary).x) + ((geometry[(triangle + 6u)]).xyz * (bary).y)) + ((geometry[(triangle + 7u)]).xyz * (bary).z));
if ((dot(interpolated, interpolated) > 1e-20)) {
local_shading = normalize(interpolated);
}
}
normal = normal_world(base, local_shading);
if ((dot(normal, geometric) < 0.0)) {
normal = (normal * -1.0);
}
var local_tangent: vec3<f32> = basis_tangent(local_shading);
var hand: f32 = 1.0;
if (((geometry[(triangle + 4u)]).w > 0.0)) {
let t: vec4<f32> = (((geometry[(triangle + 8u)] * (bary).x) + (geometry[(triangle + 9u)] * (bary).y)) + (geometry[(triangle + 10u)] * (bary).z));
local_tangent = (t).xyz;
if (((t).w < 0.0)) {
hand = -1.0;
}
}
else {
let ua: vec2<f32> = ((geometry[(triangle + 3u)]).zw - (geometry[(triangle + 3u)]).xy);
let ub: vec2<f32> = ((geometry[(triangle + 4u)]).xy - (geometry[(triangle + 3u)]).xy);
let det: f32 = (((ua).x * (ub).y) - ((ua).y * (ub).x));
if ((abs(det) > 1e-12)) {
local_tangent = (((e1 * (ub).y) - (e2 * (ua).y)) / det);
let bt: vec3<f32> = (((e2 * (ua).x) - (e1 * (ub).x)) / det);
if ((dot(cross(local_shading, local_tangent), bt) < 0.0)) {
hand = -1.0;
}
}
}
var tangent: vec3<f32> = vector_world(base, local_tangent);
tangent = (tangent - (normal * dot(normal, tangent)));
if ((dot(tangent, tangent) < 1e-20)) {
tangent = basis_tangent(normal);
}
tangent = normalize(tangent);
if (back) {
tangent = (tangent * -1.0);
hand = (hand * -1.0);
}
let bitangent: vec3<f32> = ((cross(normal, tangent) * hand) * (instances[(base + 3u)]).w);
let color: vec3<f32> = ((instances[(base + 6u)]).xyz * (sample_map((instances[(base + 10u)]).x, uv, dx, dy)).xyz);
let orm: vec4<f32> = sample_map((instances[(base + 11u)]).x, uv, dx, dy);
let metal: f32 = ((instances[(base + 9u)]).y * (orm).z);
let rough: f32 = ((instances[(base + 9u)]).x * (orm).y);
if (((instances[(base + 12u)]).x >= 0.0)) {
let map: vec3<f32> = (((sample_map((instances[(base + 12u)]).x, uv, dx, dy)).xyz * 2.0) - vec3<f32>(1.0));
let mapped: vec3<f32> = ((((tangent * (map).x) * (instances[(base + 9u)]).z) + ((bitangent * (map).y) * (instances[(base + 9u)]).z)) + (normal * (map).z));
if ((dot(mapped, mapped) > 1e-20)) {
normal = normalize(mapped);
}
}
if (((sample == u32((params[6u]).w)) && (bounce == 0u))) {
first_normal = normal;
}
radiance = (radiance + ((instances[(base + 7u)]).xyz * (sample_map((instances[(base + 13u)]).x, uv, dx, dy)).xyz));
let offset: vec3<f32> = (position + (geometric * 1e-5));
let view: vec3<f32> = (direction * -1.0);
let to_light: vec3<f32> = ((params[5u]).xyz - position);
let distance: f32 = sqrt(dot(to_light, to_light));
if ((distance > 1e-5)) {
let light_dir: vec3<f32> = (to_light / distance);
let cosine: f32 = dot(normal, light_dir);
if (((cosine > 0.0) && (dot(geometric, light_dir) > 0.0))) {
if (((trace(offset, light_dir, (distance - 2e-5), 1e-5)).x < 0.0)) {
radiance = (radiance + ((brdf(color, metal, rough, normal, view, light_dir) * (params[6u]).xyz) * (cosine / (distance * distance))));
}
}
}
let secondary: vec3<f32> = pbr_sample(normal, view, rough, random(pixel, sample, (4u + (bounce * u32((params[9u]).z))), (u32((params[5u]).w) + (u32((params[7u]).w) * 65536u))), random(pixel, sample, (2u + (bounce * u32((params[9u]).z))), (u32((params[5u]).w) + (u32((params[7u]).w) * 65536u))), random(pixel, sample, (3u + (bounce * u32((params[9u]).z))), (u32((params[5u]).w) + (u32((params[7u]).w) * 65536u))));
let pdf: f32 = pbr_pdf(normal, view, secondary, rough);
if (((pdf > 0.0) && (dot(geometric, secondary) > 0.0))) {
let occlusion: f32 = (1.0 + ((instances[(base + 9u)]).w * ((sample_map((instances[(base + 14u)]).x, uv, dx, dy)).x - 1.0)));
next_origin = offset;
next_direction = secondary;
weight = ((brdf(color, metal, rough, normal, view, secondary) * (dot(normal, secondary) / pdf)) * occlusion);
if ((((bounce + 1u) == u32((params[0u]).w)) && ((trace(offset, secondary, 1e30, 1e-5)).x < 0.0))) {
radiance = (radiance + ((brdf(color, metal, rough, normal, view, secondary) * (params[7u]).xyz) * ((dot(normal, secondary) * occlusion) / pdf)));
}
}
}
else {
var color: vec3<f32> = (instances[(base + 6u)]).xyz;
let texwidth: u32 = u32((instances[(base + 8u)]).x);
let texheight: u32 = u32((instances[(base + 8u)]).y);
if ((texwidth > 0u)) {
let ro: vec3<f32> = transform(base, origin, 1.0);
let rd: vec3<f32> = transform(base, direction, 0.0);
let bary: vec3<f32> = triangle_hit(ro, rd, triangle, 1e30);
let uvpair: vec4<f32> = geometry[(triangle + 3u)];
let lastuv: vec4<f32> = geometry[(triangle + 4u)];
let uv: vec2<f32> = ((((uvpair).xy * ((1.0 - (bary).y) - (bary).z)) + ((uvpair).zw * (bary).y)) + ((lastuv).xy * (bary).z));
let tx: u32 = min(u32((fract((uv).x) * f32(texwidth))), (texwidth - 1u));
let ty: u32 = min(u32((fract((uv).y) * f32(texheight))), (texheight - 1u));
color = (color * (geometry[((u32((instances[(base + 7u)]).w) + (ty * texwidth)) + tx)]).xyz);
}
radiance = (radiance + (instances[(base + 7u)]).xyz);
let offset: vec3<f32> = (position + (normal * 1e-5));
let to_light: vec3<f32> = ((params[5u]).xyz - position);
let distance: f32 = sqrt(dot(to_light, to_light));
let light_dir: vec3<f32> = (to_light / distance);
let cosine: f32 = max(dot(normal, light_dir), 0.0);
if (((cosine > 0.0) && (distance > 1e-5))) {
if (((trace(offset, light_dir, (distance - 2e-5), 1e-5)).x < 0.0)) {
radiance = (radiance + ((color * (params[6u]).xyz) * (cosine / ((3.1415927 * distance) * distance))));
}
}
let secondary: vec3<f32> = cosine_direction(normal, random(pixel, sample, (2u + (bounce * u32((params[9u]).z))), (u32((params[5u]).w) + (u32((params[7u]).w) * 65536u))), random(pixel, sample, (3u + (bounce * u32((params[9u]).z))), (u32((params[5u]).w) + (u32((params[7u]).w) * 65536u))));
next_origin = offset;
next_direction = secondary;
weight = color;
if ((((bounce + 1u) == u32((params[0u]).w)) && ((trace(offset, secondary, 1e30, 1e-5)).x < 0.0))) {
radiance = (radiance + (color * (params[7u]).xyz));
}
}
}
sum = (sum + (throughput * radiance));
throughput = (throughput * weight);
if ((dot(throughput, throughput) == 0.0)) {
break;
}
origin = next_origin;
direction = next_direction;
near = 1e-5;
far = 1e30;
bounce = (bounce + 1u);
}
sample = (sample + 1u);
}
output[(pixel * 2u)] = vec4<f32>((sum / (params[0u]).z), first_depth);
output[((pixel * 2u) + 1u)] = vec4<f32>(first_normal, first_instance);
}
