"""Generate portable numeric source from the retained native compatibility oracle.

This does not regenerate the oracle or reference images. The input records every
8-bit code and the unchanged source function used for the native capture.
"""
import hashlib,json,struct
from pathlib import Path
source=Path('fixtures/tiled-painting/srgb8-native-baseline.json')
reference=json.loads(source.read_text());bits=reference['bits']
assert reference['version']==0 and reference['profile']=='srgb8-compat-v1'
assert len(bits)==256 and all(isinstance(v,int) and 0<=v<=0xffffffff for v in bits)
values=[struct.unpack('<f',struct.pack('<I',v))[0] for v in bits]
assert values[0]==0 and values[-1]==1 and all(a<b for a,b in zip(values,values[1:]))
print('// Generated by scripts/generate-srgb8-compat.py; do not edit numeric values.')
print('// Input: fixtures/tiled-painting/srgb8-native-baseline.json')
print('// SHA256: '+hashlib.sha256(source.read_bytes()).hexdigest())
print('pub const LINEAR: [f32; 256] = [')
for value in bits:print(f'    f32::from_bits(0x{value:08x}),')
print('];')
