//! Reviewed operation metadata is independent of serialized private Rust layouts.
use serde::Serialize;
#[derive(Serialize)]
pub struct Operation {
    pub name: &'static str,
    pub version: u32,
    pub mutation: bool,
    pub effects: &'static str,
    pub cancellation: &'static str,
}
pub fn registry() -> Vec<Operation> {
    let mut operations = vec![
        Operation {
            name: "create_box",
            version: 0,
            mutation: true,
            effects: "author a bounded metric box on an empty entity",
            cancellation: "before publication",
        },
        Operation {
            name: "model_mesh",
            version: 0,
            mutation: true,
            effects: "apply a bounded topology operator with pinned source and durable correspondence receipt",
            cancellation: "before publication",
        },
        Operation {
            name: "set_procedural",
            version: 0,
            mutation: true,
            effects: "author a typed geometry/field graph and group assets",
            cancellation: "before publication",
        },
        Operation {
            name: "bake_procedural",
            version: 0,
            mutation: true,
            effects: "realize a pinned graph into a mesh while retaining the authored graph asset",
            cancellation: "before publication",
        },
        Operation {
            name: "set_imaging",
            version: 0,
            mutation: true,
            effects: "author color, denoising, render-view and UV bake policy",
            cancellation: "before commit",
        },
        Operation {
            name: "merge_animation",
            version: 0,
            mutation: true,
            effects: "append typed animation components atomically; reject all identity collisions",
            cancellation: "before publication",
        },
        Operation {
            name: "set_animation",
            version: 0,
            mutation: true,
            effects: "author typed clips, rigs, morphs and skinning through atomic revision-checked publication",
            cancellation: "before commit",
        },
        Operation {
            name: "set_groom",
            version: 0,
            mutation: true,
            effects: "author guides and procedural children attached by stable mesh corner identity",
            cancellation: "before commit",
        },
        Operation {
            name: "put_volume",
            version: 0,
            mutation: true,
            effects: "insert bounded sparse RGB density/emission asset",
            cancellation: "before commit",
        },
        Operation {
            name: "set_volume",
            version: 0,
            mutation: true,
            effects: "attach sparse medium through revision-checked transaction",
            cancellation: "before commit",
        },
        Operation {
            name: "put_geometry",
            version: 0,
            mutation: true,
            effects: "insert validated typed spline/point asset by content identity",
            cancellation: "before commit",
        },
        Operation {
            name: "set_geometry",
            version: 0,
            mutation: true,
            effects: "attach typed geometry to an entity through normal revision-checked publication",
            cancellation: "before commit",
        },
        Operation {
            name: "use_camera",
            version: 0,
            mutation: true,
            effects: "evaluate authored camera and select it transactionally with stable retry identity",
            cancellation: "before commit",
        },
        Operation {
            name: "put_image",
            version: 0,
            mutation: true,
            effects: "validate bounded encoded PNG/JPEG and insert immutable content",
            cancellation: "before commit",
        },
        Operation {
            name: "set_camera",
            version: 0,
            mutation: true,
            effects: "attach validated lens to authored entity",
            cancellation: "before commit",
        },
        Operation {
            name: "set_render_settings",
            version: 0,
            mutation: true,
            effects: "atomically author camera, lighting and bounded render settings",
            cancellation: "before commit",
        },
        Operation {
            name: "inspect",
            version: 0,
            mutation: false,
            effects: "read a pinned snapshot and revision",
            cancellation: "immediate",
        },
        Operation {
            name: "put_mesh",
            version: 0,
            mutation: true,
            effects: "insert validated immutable geometry by SHA-256",
            cancellation: "before commit",
        },
        Operation {
            name: "put_material",
            version: 0,
            mutation: true,
            effects: "replace explicitly addressed material",
            cancellation: "before commit",
        },
        Operation {
            name: "create_entity",
            version: 0,
            mutation: true,
            effects: "insert entity with persistent ID and explicit references",
            cancellation: "before commit",
        },
        Operation {
            name: "rename",
            version: 0,
            mutation: true,
            effects: "replace entity label; preserve identity",
            cancellation: "before commit",
        },
        Operation {
            name: "reparent",
            version: 0,
            mutation: true,
            effects: "replace parent; preserve local authored transform; reject cycles",
            cancellation: "before commit",
        },
        Operation {
            name: "set_transform",
            version: 0,
            mutation: true,
            effects: "replace ordered transform channels and affine base",
            cancellation: "before commit",
        },
        Operation {
            name: "set_material",
            version: 0,
            mutation: true,
            effects: "replace entity material reference",
            cancellation: "before commit",
        },
        Operation {
            name: "set_material_scalar",
            version: 0,
            mutation: true,
            effects: "set roughness or metallic in [0,1]; renderer profile checked separately",
            cancellation: "before commit",
        },
        Operation {
            name: "put_layer",
            version: 0,
            mutation: true,
            effects: "replace or append named sparse override layer",
            cancellation: "before commit",
        },
    ];
    operations.extend(crate::agent::registry());
    operations
}
